name: Build and Deploy GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your main branch
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install markdown2

      # 4. Build HTML from Markdown
      - name: Convert Markdown to HTML
        run: python build_md_to_html_with_toc.py

      # 5. Upload generated HTML folder as artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build  # this folder is created by your Python script

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      # Deploy artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
