name: Build and Deploy GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install markdown2

      # 4. Build HTML from Markdown
      - name: Build HTML from Markdown
        run: python build_md_to_html_with_toc.py

      # 5. Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone gh-pages branch (or create if missing)
          git clone --branch gh-pages https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY} gh-pages || \
            git clone https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY} gh-pages
          
          # Clean old files
          rm -rf gh-pages/*

          # Copy new build
          cp -r build/* gh-pages/

          # Commit and push
          cd gh-pages
          git add .
          git commit -m "Deploy site from workflow" || echo "No changes to commit"
          git push origin gh-pages
